# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY mkbsd.py /app/mkbsd.py

# Install the required packages
RUN pip install aiohttp

# Set Python to run in unbuffered mode
ENV PYTHONUNBUFFERED=1

# Run the script when the container launches
CMD ["python", "mkbsd.py"]
